services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      apt-get update && apt-get install -y gfortran
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app
